# Generated by Django 3.2.6 on 2021-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('C', 'Complete'), ('D', 'Doing'), ('R', 'Cancel')], default='D', max_length=15)),
            ],
        ),
    ]
